/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './login.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from '@angular/router';
import * as i4 from './login.component';
const styles_LoginComponent:any[] = [i0.styles];
export const RenderType_LoginComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_LoginComponent,data:{}});
export function View_LoginComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[i1.ɵpid(0,i2.DatePipe,[i1.LOCALE_ID]),(_l()(),i1.ɵted((null as any),
      [' '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),9,'div',[['class','image']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),i1.ɵdid(278528,
      (null as any),0,i2.NgStyle,[i1.KeyValueDiffers,i1.ElementRef,i1.Renderer],{ngStyle:[0,
          'ngStyle']},(null as any)),i1.ɵpod({'background-image':0}),(_l()(),i1.ɵted((null as any),
      ['\n  \n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'container-fluid'],['id','pageContainer']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n      '])),(_l()(),
      i1.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(212992,(null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,i1.ViewContainerRef,
          i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵted((null as any),['\n  \n  '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),11,'div',[['class','footer']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),8,'div',[['class',
          'container-fluid']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n      '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),5,'div',[['id','copyright']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'h4',[['class',
          'provider']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),[' © Anthony Vest, BSc Computer Science @ The University of Sunderland ',
          ''])),i1.ɵppd(2),(_l()(),i1.ɵted((null as any),['\n      '])),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵted((null as any),
          ['\n  ']))],(_ck,_v) => {
    var _co:i4.LoginComponent = _v.component;
    const currVal_0:any = _ck(_v,4,0,(('url(' + _co.background.link) + ')'));
    _ck(_v,3,0,currVal_0);
    _ck(_v,9,0);
  },(_ck,_v) => {
    var _co:i4.LoginComponent = _v.component;
    const currVal_1:any = i1.ɵunv(_v,20,0,_ck(_v,21,0,i1.ɵnov(_v,0),_co.year,'yyyy'));
    _ck(_v,20,0,currVal_1);
  });
}
export function View_LoginComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-login',([] as any[]),
      (null as any),(null as any),(null as any),View_LoginComponent_0,RenderType_LoginComponent)),
      i1.ɵdid(49152,(null as any),0,i4.LoginComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const LoginComponentNgFactory:i1.ComponentFactory<i4.LoginComponent> = i1.ɵccf('app-login',
    i4.LoginComponent,View_LoginComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYW50aG8vQWR2YW5jZWQgQ3liZXIgU2VjdXJpdHkvQXNzaWdubWVudCB0d28vQXNzaWdubWVudC9hc3NldHMvYXBwL2xvZ2luL2xvZ2luLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9hbnRoby9BZHZhbmNlZCBDeWJlciBTZWN1cml0eS9Bc3NpZ25tZW50IHR3by9Bc3NpZ25tZW50L2Fzc2V0cy9hcHAvbG9naW4vbG9naW4uY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvYW50aG8vQWR2YW5jZWQgQ3liZXIgU2VjdXJpdHkvQXNzaWdubWVudCB0d28vQXNzaWdubWVudC9hc3NldHMvYXBwL2xvZ2luL2xvZ2luLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvYW50aG8vQWR2YW5jZWQgQ3liZXIgU2VjdXJpdHkvQXNzaWdubWVudCB0d28vQXNzaWdubWVudC9hc3NldHMvYXBwL2xvZ2luL2xvZ2luLmNvbXBvbmVudC50cy5Mb2dpbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIiA8ZGl2IGNsYXNzPVwiaW1hZ2VcIiBbbmdTdHlsZV09XCJ7J2JhY2tncm91bmQtaW1hZ2UnOid1cmwoJyArIGJhY2tncm91bmQubGluayArICcpJ31cIj5cclxuICBcclxuICAgIDxkaXYgaWQ9XCJwYWdlQ29udGFpbmVyXCIgY2xhc3M9XCJjb250YWluZXItZmx1aWRcIj5cclxuICAgICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxyXG4gICAgPC9kaXY+XHJcbiAgPC9kaXY+XHJcbiAgXHJcbiAgPGRpdiBjbGFzcz1cImZvb3RlclwiPlxyXG4gICAgPGRpdiBjbGFzcz1cImNvbnRhaW5lci1mbHVpZFwiPlxyXG4gICAgICA8ZGl2IGlkPVwiY29weXJpZ2h0XCI+XHJcbiAgICAgICAgPGg0IGNsYXNzPVwicHJvdmlkZXJcIj4gJmNvcHk7IEFudGhvbnkgVmVzdCwgQlNjIENvbXB1dGVyIFNjaWVuY2UgQCBUaGUgVW5pdmVyc2l0eSBvZiBTdW5kZXJsYW5kIHt7eWVhciB8IGRhdGU6ICd5eXl5J319PC9oND5cclxuICAgICAgPC9kaXY+XHJcbiAgICA8L2Rpdj5cclxuICA8L2Rpdj5cclxuICAiLCI8YXBwLWxvZ2luPjwvYXBwLWxvZ2luPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OzBEQ0FBO01BQUEsUUFBQztNQUFBLCtFQUFBO01BQUE7VUFBQSxrQ0FBbUIseUJBQWdFO01BQUEsaUJBRWhGO01BQUE7TUFBQSw4QkFBZ0QsNkNBQzlDO2FBQUE7VUFBQTthQUFBO3NDQUFBO1VBQUEsZUFBK0IsMkNBQzNCO1VBQUEsV0FDRiw2Q0FFTjtVQUFBO1VBQUEsMERBQW9CO1VBQUEsYUFDbEI7VUFBQTtVQUFBLGdCQUE2Qiw2Q0FDM0I7VUFBQTtVQUFBLDRDQUFvQjtVQUFBLGlCQUNsQjtVQUFBO01BQXFCO1VBQUEsaUJBQXNHLDZDQUN2SDtVQUFBLGFBQ0YseUNBQ0Y7VUFBQTs7SUFiWTtJQUFuQixXQUFtQixTQUFuQjtJQUdLOzs7SUFPdUI7SUFBQTs7OztvQkNWN0I7TUFBQTthQUFBO1VBQUE7OzsifQ==
