/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './home-routing.module';
import * as i2 from './home.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/router';
import * as i5 from './home.component';
import * as i6 from '../auth.guard';
export const HomeRoutingModuleNgFactory:i0.NgModuleFactory<i1.HomeRoutingModule> = i0.ɵcmf(i1.HomeRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.HomeComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,
              i3.CommonModule,i3.CommonModule,([] as any[])),i0.ɵmpd(512,i4.RouterModule,
              i4.RouterModule,[[2,i4.ɵa],[2,i4.Router]]),i0.ɵmpd(512,i1.HomeRoutingModule,
              i1.HomeRoutingModule,([] as any[])),i0.ɵmpd(1024,i4.ROUTES,() => {
            return [[{path:'home',component:i5.HomeComponent,canActivate:[i6.AuthGuard]}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYW50aG8vQWR2YW5jZWQgQ3liZXIgU2VjdXJpdHkvQXNzaWdubWVudCB0d28vQXNzaWdubWVudC9hc3NldHMvYXBwL2hvbWUvaG9tZS1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9hbnRoby9BZHZhbmNlZCBDeWJlciBTZWN1cml0eS9Bc3NpZ25tZW50IHR3by9Bc3NpZ25tZW50L2Fzc2V0cy9hcHAvaG9tZS9ob21lLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
