/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './home.module';
import * as i2 from './home.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from './home.service';
import * as i5 from '@angular/http';
import * as i6 from '../validation/errors/error.service';
import * as i7 from '@angular/router';
import * as i8 from './home-routing.module';
import * as i9 from './home.component';
import * as i10 from '../auth.guard';
export const HomeModuleNgFactory:i0.NgModuleFactory<i1.HomeModule> = i0.ɵcmf(i1.HomeModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.HomeComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i4.HomeService,i4.HomeService,[i5.Http,i6.ErrorService]),i0.ɵmpd(512,
              i3.CommonModule,i3.CommonModule,([] as any[])),i0.ɵmpd(512,i7.RouterModule,
              i7.RouterModule,[[2,i7.ɵa],[2,i7.Router]]),i0.ɵmpd(512,i8.HomeRoutingModule,
              i8.HomeRoutingModule,([] as any[])),i0.ɵmpd(512,i1.HomeModule,i1.HomeModule,
              ([] as any[])),i0.ɵmpd(1024,i7.ROUTES,() => {
            return [[{path:'home',component:i9.HomeComponent,canActivate:[i10.AuthGuard]}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYW50aG8vQWR2YW5jZWQgQ3liZXIgU2VjdXJpdHkvQXNzaWdubWVudCB0d28vQXNzaWdubWVudC9hc3NldHMvYXBwL2hvbWUvaG9tZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvYW50aG8vQWR2YW5jZWQgQ3liZXIgU2VjdXJpdHkvQXNzaWdubWVudCB0d28vQXNzaWdubWVudC9hc3NldHMvYXBwL2hvbWUvaG9tZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
