/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.dropdown[_ngcontent-%COMP%] {\r\n	float: left;\r\n	width:160px;\r\n	margin-right: auto;\r\n}\r\n\r\n.liftup[_ngcontent-%COMP%]{\r\n	margin-bottom: 20px;\r\n	text-align: center\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYW50aG8vQWR2YW5jZWQgQ3liZXIgU2VjdXJpdHkvQXNzaWdubWVudCB0d28vQXNzaWdubWVudC9hc3NldHMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2FudGhvL0FkdmFuY2VkIEN5YmVyIFNlY3VyaXR5L0Fzc2lnbm1lbnQgdHdvL0Fzc2lnbm1lbnQvYXNzZXRzL2FwcC9ob21lL2hvbWUuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
