/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app-routing.module';
import * as i2 from './validation/errors/error.component.ngfactory';
import * as i3 from './validation/success/success.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '@angular/router';
import * as i6 from './can-deactivate.guard';
import * as i7 from './validation/errors/error.component';
import * as i8 from './validation/success/success.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ErrorComponentNgFactory,i3.SuccessComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i4.NgLocalization,i4.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i5.ActivatedRoute,i5.ɵf,[i5.Router]),i0.ɵmpd(4608,
          i5.NoPreloading,i5.NoPreloading,([] as any[])),i0.ɵmpd(6144,i5.PreloadingStrategy,
          (null as any),[i5.NoPreloading]),i0.ɵmpd(135680,i5.RouterPreloader,i5.RouterPreloader,
          [i5.Router,i0.NgModuleFactoryLoader,i0.Compiler,i0.Injector,i5.PreloadingStrategy]),
          i0.ɵmpd(4608,i5.PreloadAllModules,i5.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,
              i0.NgProbeToken,() => {
                return [i5.ɵb()];
              },([] as any[])),i0.ɵmpd(4608,i5.ɵg,i5.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i5.ɵh(p0_0)];
              },[i5.ɵg]),i0.ɵmpd(5120,i5.ROUTER_INITIALIZER,i5.ɵi,[i5.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i5.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i6.CanDeactivateGuard,i6.CanDeactivateGuard,
              ([] as any[])),i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i5.ɵa,i5.ɵd,[[3,i5.Router]]),i0.ɵmpd(512,i5.UrlSerializer,i5.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i5.ChildrenOutletContexts,i5.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i5.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i4.LocationStrategy,i5.ɵc,[i4.PlatformLocation,[2,i4.APP_BASE_HREF],
              i5.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i4.Location,i4.Location,[i4.LocationStrategy]),
          i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,[i0.Compiler,
              [2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i5.ROUTES,() => {
            return [[{path:'error',component:i7.ErrorComponent},{path:'success',component:i8.SuccessComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i5.Router,i5.ɵe,[i0.ApplicationRef,i5.UrlSerializer,
              i5.ChildrenOutletContexts,i4.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i5.ROUTES,i5.ROUTER_CONFIGURATION,[2,i5.UrlHandlingStrategy],
              [2,i5.RouteReuseStrategy]]),i0.ɵmpd(512,i5.RouterModule,i5.RouterModule,
              [[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYW50aG8vQWR2YW5jZWQgQ3liZXIgU2VjdXJpdHkvQXNzaWdubWVudCB0d28vQXNzaWdubWVudC9hc3NldHMvYXBwL2FwcC1yb3V0aW5nLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9hbnRoby9BZHZhbmNlZCBDeWJlciBTZWN1cml0eS9Bc3NpZ25tZW50IHR3by9Bc3NpZ25tZW50L2Fzc2V0cy9hcHAvYXBwLXJvdXRpbmcubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
